//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lab_6_client.StudentNotesModifyService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="StudentNotesModifyService.IStudentNotesModify")]
    public interface IStudentNotesModify {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentNotesModify/Insert", ReplyAction="http://tempuri.org/IStudentNotesModify/InsertResponse")]
        void Insert(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentNotesModify/Insert", ReplyAction="http://tempuri.org/IStudentNotesModify/InsertResponse")]
        System.Threading.Tasks.Task InsertAsync(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentNotesModify/Update", ReplyAction="http://tempuri.org/IStudentNotesModify/UpdateResponse")]
        void Update(int id, string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentNotesModify/Update", ReplyAction="http://tempuri.org/IStudentNotesModify/UpdateResponse")]
        System.Threading.Tasks.Task UpdateAsync(int id, string name);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IStudentNotesModifyChannel : lab_6_client.StudentNotesModifyService.IStudentNotesModify, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class StudentNotesModifyClient : System.ServiceModel.ClientBase<lab_6_client.StudentNotesModifyService.IStudentNotesModify>, lab_6_client.StudentNotesModifyService.IStudentNotesModify {
        
        public StudentNotesModifyClient() {
        }
        
        public StudentNotesModifyClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public StudentNotesModifyClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StudentNotesModifyClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StudentNotesModifyClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void Insert(string name) {
            base.Channel.Insert(name);
        }
        
        public System.Threading.Tasks.Task InsertAsync(string name) {
            return base.Channel.InsertAsync(name);
        }
        
        public void Update(int id, string name) {
            base.Channel.Update(id, name);
        }
        
        public System.Threading.Tasks.Task UpdateAsync(int id, string name) {
            return base.Channel.UpdateAsync(id, name);
        }
    }
}
